# platform :ios, '14.0'

# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# target 'SenseOfSeeing' do
#   # Pods for SenseOfSeeing
#   # pod 'React', :path => '../node_modules/react-native/'
#   # pod 'React-Core', :path => '../node_modules/react-native'
#   # pod 'React-DevSupport', :path => '../node_modules/react-native/'
#   # pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   # pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   # pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   # pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   # pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   # pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   # pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   # pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   # pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   # pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

#   # pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   # pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   # pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   # pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


#   # pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
#   # pod 'React', path: '../node_modules/react-native', :subspecs => [
#   #       'Core',
#   #       # 'RCTActionSheet',
#   #       # 'RCTAnimation',
#   #       # 'RCTGeolocation',
#   #       # 'RCTImage',
#   #       # 'RCTLinkingIOS',
#   #     ]

#   # pod 'React', :path => '../node_modules/react-native/'
#   pod 'React-Core', :path => '../node_modules/react-native'
#   pod 'React-DevSupport', :path => '../node_modules/react-native'
#   pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon'
#   pod 'FBLazyVector', :path => '../node_modules/react-native/Libraries/FBLazyVector'
#   pod 'RCTRequired', :path => '../node_modules/react-native/Libraries/RCTRequired'
#   pod 'FBReactNativeSpec', :path => '../node_modules/react-native/Libraries/FBReactNativeSpec'
#   pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
#   pod 'RCTTypeSafety', :path => '../node_modules/react-native/Libraries/TypeSafety'
#   pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#   pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#   pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#   pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#   pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#   pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#   pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#   pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#   pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#   pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

#   pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#   pod 'React-callinvoker', :path => '../node_modules/react-native/ReactCommon/callinvoker'
#   pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#   pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#   pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#   pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

#   pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#   pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#   pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'



#   pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

pod 'RNSVG', :path => '../node_modules/react-native-svg'

#   target 'SenseOfSeeingTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

#   use_native_modules!
# end

# target 'SenseOfSeeing-tvOS' do
#   # Pods for SenseOfSeeing-tvOS

#   target 'SenseOfSeeing-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '14.0'

target 'SenseOfSeeing' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])


  target 'SenseOfSeeingTests' do
    inherit! :complete
  end  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

# target 'RnDiffApp-tvOS' do
#   inherit! :search_paths
#   # Pods for testing
# end


